### ISSUE TITLE
Crash in keychain initialize on Python 3.11

### ISSUE THREAD

**Issue by adgeg** [codemagic-ci-cd/cli-tools#294] opened 2022-12-20 11:13 UTC
Hi, 

First, thanks for your great job!
This issue seems equivalent [to this one](https://github.com/codemagic-ci-cd/cli-tools/issues/282).

On Python 3.11, the output of `keychain initialize` is the following:
```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/keychain", line 5, in <module>
    from codemagic.tools import Keychain
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/codemagic/tools/__init__.py", line 1, in <module>
    from .android_app_bundle import AndroidAppBundle
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/codemagic/tools/android_app_bundle.py", line 35, in <module>
    class AndroidAppBundleArgument(cli.Argument):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/codemagic/tools/android_app_bundle.py", line 65, in AndroidAppBundleArgument
    KEYSTORE_PATH_REQUIRED = KEYSTORE_PATH.duplicate(argparse_kwargs={'required': True})
                             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'duplicate'
```

Steps to reproduce on a Github action:
```yaml
on:
  pull_request:

jobs:
  ko-on-python-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Codemagic CLI tools
        shell: bash
        run: |
          pip3 install codemagic-cli-tools
          xcrun xcodebuild -version

      - name: Set up a temporary keychain for code signing
        shell: bash
        run: |
          keychain initialize


  ok-on-python-10:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Codemagic CLI tools
        shell: bash
        run: |
          pip3 install codemagic-cli-tools
          xcrun xcodebuild -version

      - name: Set up a temporary keychain for code signing
        shell: bash
        run: |
          keychain initialize
```

Thanks for your support :)

**Comment by priitlatt** [comment] 2022-12-20 11:24
Duplicate of #293.

**Closed by priitlatt** 2022-12-20 11:24 UTC
