### ISSUE TITLE
Get latest build number for custom track

### ISSUE THREAD

**Issue by ankitjainOfficial** [codemagic-ci-cd/cli-tools#166] opened 2021-11-22 11:43 UTC
Right now, when getting latest build number, only some tracks are showing. But, I've custom tracks, where the build number has increased. How can configure to get latest build number from custom tracks as well?

**Comment by helinanever** [comment] 2022-04-07 08:58
Duplicate of https://github.com/codemagic-ci-cd/cli-tools/issues/152

**Closed** 2022-04-07 08:57 UTC
