### ISSUE TITLE
Remove usage of distutils, no support for Python 3.12+

### ISSUE THREAD

**Issue by Oidlichtnwoada** [codemagic-ci-cd/cli-tools#368] opened 2023-11-06 10:34 UTC
please remove the usage of distutils to support python 3.12+

from distutils.version import LooseVersion

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.12.0/x64/bin/keychain", line 5, in <module>
    from codemagic.tools import Keychain
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/codemagic/tools/__init__.py", line 1, in <module>
    from .android_app_bundle import AndroidAppBundle
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/codemagic/tools/android_app_bundle.py", line 12, in <module>
    from codemagic.models import AndroidSigningInfo
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/codemagic/models/__init__.py", line 6, in <module>
    from .code_sign_entitlements import CodeSignEntitlements
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/codemagic/models/code_sign_entitlements.py", line 8, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/Users/runner/work/energy-assistant/energy-assistant/apps/energy-assistant-b2c/ios/App/../../../../scripts/build_helpers.py", line 251, in <module>
    main()
  File "/Users/runner/work/energy-assistant/energy-assistant/apps/energy-assistant-b2c/ios/App/../../../../scripts/build_helpers.py", line 247, in main
    start_requested_job(args, flavor)
  File "/Users/runner/work/energy-assistant/energy-assistant/apps/energy-assistant-b2c/ios/App/../../../../scripts/build_helpers.py", line 234, in start_requested_job
    build_ios_app(args.project, flavor)
  File "/Users/runner/work/energy-assistant/energy-assistant/apps/energy-assistant-b2c/ios/App/../../../../scripts/build_helpers.py", line 189, in build_ios_app
    subprocess.run('keychain initialize', shell=True, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'keychain initialize' returned non-zero exit status 1.

**Comment by priitlatt** [comment] 2023-11-06 13:04
Duplicate of #369.

**Closed by priitlatt** 2023-11-06 13:04 UTC

**Comment by priitlatt** [comment] 2023-11-06 14:52
@Oidlichtnwoada, [version 0.47.0](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.47.0) fixes this.
